-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_sobel_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_80_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mul_ln66 : IN STD_LOGIC_VECTOR (63 downto 0);
    cols_cast6 : IN STD_LOGIC_VECTOR (31 downto 0);
    src : IN STD_LOGIC_VECTOR (63 downto 0);
    cols_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln77 : IN STD_LOGIC_VECTOR (31 downto 0);
    sub2 : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln77 : IN STD_LOGIC_VECTOR (30 downto 0);
    dst : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of sobel_sobel_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_80_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_2 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000010";
    constant ap_const_lv33_1 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage8 : signal is "none";
    signal ap_block_state18_pp0_stage8_iter1 : BOOLEAN;
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal icmp_ln77_reg_833 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage8 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage8 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal gmem_blk_n_B : STD_LOGIC;
    signal icmp_ln80_1_reg_863 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_1_reg_863_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_blk_n_W : STD_LOGIC;
    signal gmem_blk_n_AW : STD_LOGIC;
    signal or_ln77_reg_843 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_223 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state10_io : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln77_cast_fu_240_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln77_cast_reg_807 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln77_cast_fu_244_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln77_cast_reg_812 : STD_LOGIC_VECTOR (63 downto 0);
    signal cols_cast_cast_fu_248_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal cols_cast_cast_reg_817 : STD_LOGIC_VECTOR (62 downto 0);
    signal cols_cast6_cast_fu_252_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal cols_cast6_cast_reg_823 : STD_LOGIC_VECTOR (32 downto 0);
    signal indvar_flatten_load_reg_828 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state20_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln77_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln77_reg_833_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln77_reg_833_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_837 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln77_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln77_1_fu_317_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln77_1_reg_847 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln80_fu_325_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln80_reg_853 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state21_pp0_stage2_iter2 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal icmp_ln80_1_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_1_reg_863_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_1_reg_863_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_236_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal mul_ln77_reg_867 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_block_state22_pp0_stage3_iter2 : BOOLEAN;
    signal ap_block_state31_pp0_stage3_iter3 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal add_ln86_2_fu_369_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln86_2_reg_873 : STD_LOGIC_VECTOR (32 downto 0);
    signal gmem_addr_reg_878 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state23_pp0_stage4_iter2 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal add_ln86_fu_410_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln86_reg_883 : STD_LOGIC_VECTOR (62 downto 0);
    signal gmem_addr_1_reg_895 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_predicate_op97_writereq_state6 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_state15_pp0_stage5_iter1 : BOOLEAN;
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal empty_22_fu_447_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal empty_22_reg_901 : STD_LOGIC_VECTOR (62 downto 0);
    signal gmem_addr_2_reg_906 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_state16_pp0_stage6_iter1 : BOOLEAN;
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal gmem_addr_3_reg_912 : STD_LOGIC_VECTOR (63 downto 0);
    signal sobel_kernel_reg_918 : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_kernel_1_reg_923 : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_kernel_2_reg_928 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state17_pp0_stage7_iter1 : BOOLEAN;
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal sobel_kernel_3_reg_933 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage8_11001 : BOOLEAN;
    signal sobel_kernel_4_reg_938 : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_kernel_5_reg_943 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_pix_5_fu_525_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal out_pix_5_reg_948 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln34_fu_552_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln34_reg_953 : STD_LOGIC_VECTOR (9 downto 0);
    signal sobel_kernel_6_reg_958 : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_kernel_7_reg_963 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_x_fu_626_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_x_reg_969 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_pix_4_fu_664_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal out_pix_4_reg_975 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_reg_980 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_986 : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_2_fu_748_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_2_reg_991 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_phi_mux_first_iter_0_phi_fu_228_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal add_ln77_2_fu_387_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_20_fu_436_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_23_fu_454_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_26_fu_469_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage7_01001 : BOOLEAN;
    signal col_fu_104 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln80_fu_340_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar3_fu_108 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln80_1_fu_422_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_fu_112 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal indvar_flatten_fu_116 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln77_fu_331_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_236_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_236_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln80_1_fu_290_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln77_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln77_1_fu_311_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln80_2_fu_346_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln77_1_fu_384_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln77_fu_377_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln80_fu_398_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln86_fu_407_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln86_1_fu_402_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln86_cast_fu_433_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast10_fu_451_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp3_fu_465_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal M00_fu_481_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal M01_fu_492_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln12_fu_503_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln13_fu_506_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal S00_fu_509_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln12_fu_515_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln10_fu_488_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal A00_fu_519_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln11_fu_499_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal M00_1_fu_531_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln34_1_fu_542_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln34_fu_548_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln32_fu_538_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln13_1_fu_564_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal out_pix_6_fu_567_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln12_2_fu_561_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal out_pix_fu_572_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_586_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_578_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln23_fu_596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_fu_612_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln27_fu_602_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal M01_1_fu_634_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln37_fu_645_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln33_fu_641_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln12_1_fu_558_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln39_fu_654_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln39_fu_660_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal out_pix_7_fu_648_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_678_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln49_fu_697_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln49_fu_710_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln49_fu_702_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln49_fu_694_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_y_fu_714_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln58_1_fu_725_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln58_fu_722_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal temp_fu_734_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_fu_740_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_1_fu_729_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_236_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter2_stage3 : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_idle_pp0_1to3 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_236_p00 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component sobel_mul_31ns_32s_63_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (62 downto 0) );
    end component;


    component sobel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_31ns_32s_63_2_1_U1 : component sobel_mul_31ns_32s_63_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 32,
        dout_WIDTH => 63)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_236_p0,
        din1 => grp_fu_236_p1,
        ce => grp_fu_236_ce,
        dout => grp_fu_236_p2);

    flow_control_loop_pipe_sequential_init_U : component sobel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage8,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage8)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage3))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage3))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    col_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                col_fu_104 <= ap_const_lv31_1;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                col_fu_104 <= select_ln80_fu_340_p3;
            end if; 
        end if;
    end process;

    first_iter_0_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                first_iter_0_reg_223 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_0_reg_223 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    indvar3_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar3_fu_108 <= ap_const_lv31_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001))) then 
                indvar3_fu_108 <= add_ln80_1_fu_422_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_fu_116 <= ap_const_lv64_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                indvar_flatten_fu_116 <= add_ln77_fu_331_p2;
            end if; 
        end if;
    end process;

    indvar_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_fu_112 <= ap_const_lv31_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                indvar_fu_112 <= select_ln77_1_reg_847;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                add_ln34_reg_953 <= add_ln34_fu_552_p2;
                icmp_ln80_1_reg_863 <= icmp_ln80_1_fu_350_p2;
                icmp_ln80_1_reg_863_pp0_iter1_reg <= icmp_ln80_1_reg_863;
                icmp_ln80_1_reg_863_pp0_iter2_reg <= icmp_ln80_1_reg_863_pp0_iter1_reg;
                icmp_ln80_1_reg_863_pp0_iter3_reg <= icmp_ln80_1_reg_863_pp0_iter2_reg;
                out_pix_5_reg_948 <= out_pix_5_fu_525_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln80_reg_853 <= add_ln80_fu_325_p2;
                icmp_ln77_reg_833 <= icmp_ln77_fu_282_p2;
                icmp_ln77_reg_833_pp0_iter1_reg <= icmp_ln77_reg_833;
                icmp_ln77_reg_833_pp0_iter2_reg <= icmp_ln77_reg_833_pp0_iter1_reg;
                icmp_ln80_reg_837 <= icmp_ln80_fu_294_p2;
                indvar_flatten_load_reg_828 <= indvar_flatten_fu_116;
                or_ln77_reg_843 <= or_ln77_fu_305_p2;
                select_ln77_1_reg_847 <= select_ln77_1_fu_317_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then
                add_ln86_2_reg_873 <= add_ln86_2_fu_369_p2;
                mul_ln77_reg_867 <= grp_fu_236_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001))) then
                add_ln86_reg_883 <= add_ln86_fu_410_p2;
                gmem_addr_reg_878 <= add_ln77_2_fu_387_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cols_cast6_cast_reg_823 <= cols_cast6_cast_fu_252_p1;
                cols_cast_cast_reg_817 <= cols_cast_cast_fu_248_p1;
                sext_ln77_cast_reg_812 <= sext_ln77_cast_fu_244_p1;
                    zext_ln77_cast_reg_807(30 downto 0) <= zext_ln77_cast_fu_240_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001))) then
                empty_22_reg_901 <= empty_22_fu_447_p2;
                g_x_reg_969 <= g_x_fu_626_p3;
                gmem_addr_1_reg_895 <= empty_20_fu_436_p2;
                icmp_ln45_reg_986 <= icmp_ln45_fu_688_p2;
                out_pix_4_reg_975 <= out_pix_4_fu_664_p2;
                tmp_2_reg_980 <= out_pix_4_fu_664_p2(10 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001))) then
                gmem_addr_2_reg_906 <= empty_23_fu_454_p2;
                gmem_addr_3_reg_912 <= empty_26_fu_469_p2;
                sobel_2_reg_991 <= sobel_2_fu_748_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001))) then
                sobel_kernel_1_reg_923 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001))) then
                sobel_kernel_2_reg_928 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001))) then
                sobel_kernel_3_reg_933 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                sobel_kernel_4_reg_938 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                sobel_kernel_5_reg_943 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then
                sobel_kernel_6_reg_958 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001))) then
                sobel_kernel_7_reg_963 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001))) then
                sobel_kernel_reg_918 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    zext_ln77_cast_reg_807(63 downto 31) <= "000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage8_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter2_stage3, ap_idle_pp0_0to1, ap_idle_pp0_1to3, ap_done_pending_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to3 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage3))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    A00_fu_519_p2 <= std_logic_vector(signed(sext_ln12_fu_515_p1) - signed(zext_ln10_fu_488_p1));
    M00_1_fu_531_p3 <= (sobel_kernel_1_reg_923 & ap_const_lv1_0);
    M00_fu_481_p3 <= (sobel_kernel_3_reg_933 & ap_const_lv1_0);
    M01_1_fu_634_p3 <= (sobel_kernel_6_reg_958 & ap_const_lv1_0);
    M01_fu_492_p3 <= (sobel_kernel_4_reg_938 & ap_const_lv1_0);
    S00_fu_509_p2 <= std_logic_vector(unsigned(zext_ln12_fu_503_p1) - unsigned(zext_ln13_fu_506_p1));
    add_ln34_1_fu_542_p2 <= std_logic_vector(unsigned(zext_ln13_fu_506_p1) + unsigned(zext_ln12_fu_503_p1));
    add_ln34_fu_552_p2 <= std_logic_vector(unsigned(zext_ln34_fu_548_p1) + unsigned(zext_ln32_fu_538_p1));
    add_ln39_fu_654_p2 <= std_logic_vector(unsigned(zext_ln33_fu_641_p1) + unsigned(zext_ln12_1_fu_558_p1));
    add_ln77_1_fu_311_p2 <= std_logic_vector(unsigned(indvar_fu_112) + unsigned(ap_const_lv31_1));
    add_ln77_2_fu_387_p2 <= std_logic_vector(signed(sext_ln77_1_fu_384_p1) + signed(dst));
    add_ln77_fu_331_p2 <= std_logic_vector(unsigned(indvar_flatten_load_reg_828) + unsigned(ap_const_lv64_1));
    add_ln80_1_fu_422_p2 <= std_logic_vector(unsigned(select_ln77_fu_377_p3) + unsigned(ap_const_lv31_1));
    add_ln80_fu_325_p2 <= std_logic_vector(unsigned(col_fu_104) + unsigned(ap_const_lv31_1));
    add_ln86_1_fu_402_p2 <= std_logic_vector(signed(mul_ln77_reg_867) + signed(zext_ln80_fu_398_p1));
    add_ln86_2_fu_369_p2 <= std_logic_vector(signed(cols_cast6_cast_reg_823) + signed(ap_const_lv33_1));
        add_ln86_cast_fu_433_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln86_reg_883),64));

    add_ln86_fu_410_p2 <= std_logic_vector(signed(sext_ln86_fu_407_p1) + signed(add_ln86_1_fu_402_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
    ap_CS_fsm_pp0_stage8 <= ap_CS_fsm(8);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state10_io, ap_block_state19_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state10_io, ap_block_state19_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state19_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_io)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state20_pp0_stage1_iter2)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state20_pp0_stage1_iter2));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state20_pp0_stage1_iter2)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state20_pp0_stage1_iter2));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state21_pp0_stage2_iter2)
    begin
                ap_block_pp0_stage2_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state21_pp0_stage2_iter2));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state21_pp0_stage2_iter2)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state21_pp0_stage2_iter2));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, m_axi_gmem_ARREADY, ap_block_state22_pp0_stage3_iter2, ap_block_state31_pp0_stage3_iter3)
    begin
                ap_block_pp0_stage3_11001 <= (((m_axi_gmem_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state31_pp0_stage3_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state22_pp0_stage3_iter2)));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, m_axi_gmem_ARREADY, ap_block_state22_pp0_stage3_iter2, ap_block_state31_pp0_stage3_iter3)
    begin
                ap_block_pp0_stage3_subdone <= (((m_axi_gmem_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state31_pp0_stage3_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state22_pp0_stage3_iter2)));
    end process;

        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state23_pp0_stage4_iter2)
    begin
                ap_block_pp0_stage4_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state23_pp0_stage4_iter2));
    end process;


    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state23_pp0_stage4_iter2)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state23_pp0_stage4_iter2));
    end process;

        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state6_io, ap_block_state15_pp0_stage5_iter1)
    begin
                ap_block_pp0_stage5_11001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage5_iter1)));
    end process;


    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state6_io, ap_block_state15_pp0_stage5_iter1)
    begin
                ap_block_pp0_stage5_subdone <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage5_iter1)));
    end process;

        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state7_io, ap_block_state16_pp0_stage6_iter1)
    begin
                ap_block_pp0_stage6_11001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage6_iter1)));
    end process;


    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_state7_io, ap_block_state16_pp0_stage6_iter1)
    begin
                ap_block_pp0_stage6_subdone <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage6_iter1)));
    end process;

        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state17_pp0_stage7_iter1)
    begin
                ap_block_pp0_stage7_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_pp0_stage7_iter1));
    end process;


    ap_block_pp0_stage7_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, m_axi_gmem_WREADY, ap_block_state17_pp0_stage7_iter1)
    begin
                ap_block_pp0_stage7_11001 <= (((m_axi_gmem_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_pp0_stage7_iter1)));
    end process;


    ap_block_pp0_stage7_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, m_axi_gmem_WREADY, ap_block_state17_pp0_stage7_iter1)
    begin
                ap_block_pp0_stage7_subdone <= (((m_axi_gmem_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_pp0_stage7_iter1)));
    end process;

        ap_block_pp0_stage8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage8_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state18_pp0_stage8_iter1)
    begin
                ap_block_pp0_stage8_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state18_pp0_stage8_iter1));
    end process;


    ap_block_pp0_stage8_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state18_pp0_stage8_iter1)
    begin
                ap_block_pp0_stage8_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state18_pp0_stage8_iter1));
    end process;


    ap_block_state10_io_assign_proc : process(m_axi_gmem_ARREADY, icmp_ln77_reg_833)
    begin
                ap_block_state10_io <= ((m_axi_gmem_ARREADY = ap_const_logic_0) and (icmp_ln77_reg_833 = ap_const_lv1_0));
    end process;


    ap_block_state15_pp0_stage5_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state15_pp0_stage5_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state16_pp0_stage6_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state16_pp0_stage6_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state17_pp0_stage7_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state17_pp0_stage7_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state18_pp0_stage8_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state18_pp0_stage8_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state19_pp0_stage0_iter2_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state19_pp0_stage0_iter2 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state20_pp0_stage1_iter2_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state20_pp0_stage1_iter2 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state21_pp0_stage2_iter2_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state21_pp0_stage2_iter2 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state22_pp0_stage3_iter2_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state22_pp0_stage3_iter2 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state23_pp0_stage4_iter2_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state23_pp0_stage4_iter2 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;


    ap_block_state31_pp0_stage3_iter3_assign_proc : process(m_axi_gmem_BVALID, icmp_ln80_1_reg_863_pp0_iter3_reg)
    begin
                ap_block_state31_pp0_stage3_iter3 <= ((m_axi_gmem_BVALID = ap_const_logic_0) and (icmp_ln80_1_reg_863_pp0_iter3_reg = ap_const_lv1_0));
    end process;


    ap_block_state6_io_assign_proc : process(m_axi_gmem_AWREADY, ap_predicate_op97_writereq_state6)
    begin
                ap_block_state6_io <= ((m_axi_gmem_AWREADY = ap_const_logic_0) and (ap_predicate_op97_writereq_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_io_assign_proc : process(m_axi_gmem_ARREADY, icmp_ln77_reg_833)
    begin
                ap_block_state7_io <= ((m_axi_gmem_ARREADY = ap_const_logic_0) and (icmp_ln77_reg_833 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage8_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_subdone, icmp_ln77_reg_833)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (icmp_ln77_reg_833 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
            ap_condition_exit_pp0_iter0_stage8 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage3_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage3, icmp_ln77_reg_833_pp0_iter2_reg, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln77_reg_833_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
            ap_condition_exit_pp0_iter2_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage8;

    ap_phi_mux_first_iter_0_phi_fu_228_p4_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln77_reg_833, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, first_iter_0_reg_223)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            ap_phi_mux_first_iter_0_phi_fu_228_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_0_phi_fu_228_p4 <= first_iter_0_reg_223;
        end if; 
    end process;


    ap_predicate_op97_writereq_state6_assign_proc : process(icmp_ln77_reg_833, or_ln77_reg_843)
    begin
                ap_predicate_op97_writereq_state6 <= ((or_ln77_reg_843 = ap_const_lv1_1) and (icmp_ln77_reg_833 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

        cols_cast6_cast_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cols_cast6),33));

        cols_cast_cast_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cols_cast),63));

    empty_20_fu_436_p2 <= std_logic_vector(signed(add_ln86_cast_fu_433_p1) + signed(src));
    empty_22_fu_447_p2 <= std_logic_vector(signed(add_ln86_reg_883) + signed(cols_cast_cast_reg_817));
    empty_23_fu_454_p2 <= std_logic_vector(signed(p_cast10_fu_451_p1) + signed(src));
    empty_26_fu_469_p2 <= std_logic_vector(unsigned(tmp3_fu_465_p2) + unsigned(p_cast10_fu_451_p1));
    g_x_fu_626_p3 <= 
        select_ln27_fu_612_p3 when (or_ln27_fu_620_p2(0) = '1') else 
        trunc_ln27_fu_602_p1;
    g_y_fu_714_p3 <= 
        select_ln49_fu_702_p3 when (or_ln49_fu_710_p2(0) = '1') else 
        trunc_ln49_fu_694_p1;

    gmem_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, m_axi_gmem_ARREADY, icmp_ln77_reg_833, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage6)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3)))) then 
            gmem_blk_n_AR <= m_axi_gmem_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter0, m_axi_gmem_AWREADY, icmp_ln77_reg_833, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, or_ln77_reg_843)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (or_ln77_reg_843 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage5))) then 
            gmem_blk_n_AW <= m_axi_gmem_AWREADY;
        else 
            gmem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem_BVALID, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, icmp_ln80_1_reg_863_pp0_iter3_reg)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln80_1_reg_863_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3))) then 
            gmem_blk_n_B <= m_axi_gmem_BVALID;
        else 
            gmem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage8, m_axi_gmem_RVALID, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7, ap_block_pp0_stage0, ap_block_pp0_stage8, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7)) or ((ap_enable_reg_pp0_iter1 
    = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6)))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_WREADY, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7))) then 
            gmem_blk_n_W <= m_axi_gmem_WREADY;
        else 
            gmem_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_236_ce_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)))) then 
            grp_fu_236_ce <= ap_const_logic_1;
        else 
            grp_fu_236_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_236_p0 <= grp_fu_236_p00(31 - 1 downto 0);
    grp_fu_236_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln77_1_reg_847),63));
    grp_fu_236_p1 <= cols_cast_cast_reg_817(32 - 1 downto 0);
    icmp_ln23_fu_596_p2 <= "1" when (signed(tmp_1_fu_586_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln45_fu_688_p2 <= "1" when (signed(tmp_3_fu_678_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln77_fu_282_p2 <= "1" when (indvar_flatten_fu_116 = mul_ln66) else "0";
    icmp_ln80_1_fu_350_p2 <= "1" when (signed(zext_ln80_2_fu_346_p1) < signed(sub2)) else "0";
    icmp_ln80_fu_294_p2 <= "1" when (signed(zext_ln80_1_fu_290_p1) < signed(sub2)) else "0";

    m_axi_gmem_ARADDR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, icmp_ln77_reg_833, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_block_pp0_stage3_11001, gmem_addr_1_reg_895, gmem_addr_2_reg_906, ap_block_pp0_stage6_11001, gmem_addr_3_reg_912)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
            m_axi_gmem_ARADDR <= gmem_addr_3_reg_912;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_ARADDR <= gmem_addr_2_reg_906;
        elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001))) then 
            m_axi_gmem_ARADDR <= gmem_addr_1_reg_895;
        else 
            m_axi_gmem_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv64_3(32 - 1 downto 0);
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, icmp_ln77_reg_833, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage6_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln77_reg_833 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)))) then 
            m_axi_gmem_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_AWADDR <= gmem_addr_reg_878;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= zext_ln77_cast_reg_807(32 - 1 downto 0);
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;

    m_axi_gmem_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage5, ap_predicate_op97_writereq_state6, ap_block_pp0_stage5_11001)
    begin
        if (((ap_predicate_op97_writereq_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001))) then 
            m_axi_gmem_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem_BREADY_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, icmp_ln80_1_reg_863_pp0_iter3_reg, ap_block_pp0_stage3_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln80_1_reg_863_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
            m_axi_gmem_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_block_pp0_stage5_11001, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001, ap_block_pp0_stage8_11001)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001)) 
    or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001)))) then 
            m_axi_gmem_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_WDATA <= sobel_2_reg_991;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv1_1;
    m_axi_gmem_WUSER <= ap_const_lv1_0;

    m_axi_gmem_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001))) then 
            m_axi_gmem_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln27_fu_620_p2 <= (tmp_fu_578_p3 or icmp_ln23_fu_596_p2);
    or_ln49_fu_710_p2 <= (tmp_2_reg_980 or icmp_ln45_reg_986);
    or_ln77_fu_305_p2 <= (xor_ln77_fu_299_p2 or ap_phi_mux_first_iter_0_phi_fu_228_p4);
    out_pix_4_fu_664_p2 <= std_logic_vector(unsigned(zext_ln39_fu_660_p1) + unsigned(out_pix_7_fu_648_p2));
    out_pix_5_fu_525_p2 <= std_logic_vector(unsigned(A00_fu_519_p2) + unsigned(zext_ln11_fu_499_p1));
    out_pix_6_fu_567_p2 <= std_logic_vector(unsigned(out_pix_5_reg_948) - unsigned(zext_ln13_1_fu_564_p1));
    out_pix_7_fu_648_p2 <= std_logic_vector(unsigned(zext_ln13_1_fu_564_p1) - unsigned(zext_ln37_fu_645_p1));
    out_pix_fu_572_p2 <= std_logic_vector(unsigned(out_pix_6_fu_567_p2) + unsigned(zext_ln12_2_fu_561_p1));
        p_cast10_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_22_reg_901),64));

    select_ln27_fu_612_p3 <= 
        ap_const_lv8_FF when (xor_ln27_fu_606_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln49_fu_702_p3 <= 
        ap_const_lv8_FF when (xor_ln49_fu_697_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln77_1_fu_317_p3 <= 
        indvar_fu_112 when (icmp_ln80_fu_294_p2(0) = '1') else 
        add_ln77_1_fu_311_p2;
    select_ln77_fu_377_p3 <= 
        indvar3_fu_108 when (icmp_ln80_reg_837(0) = '1') else 
        ap_const_lv31_0;
    select_ln80_fu_340_p3 <= 
        add_ln80_reg_853 when (icmp_ln80_reg_837(0) = '1') else 
        ap_const_lv31_2;
        sext_ln12_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(S00_fu_509_p2),11));

        sext_ln77_1_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln77_reg_867),64));

        sext_ln77_cast_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln77),64));

        sext_ln86_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln86_2_reg_873),63));

    sobel_1_fu_729_p2 <= std_logic_vector(unsigned(g_y_fu_714_p3) + unsigned(g_x_reg_969));
    sobel_2_fu_748_p3 <= 
        ap_const_lv8_FF when (tmp_4_fu_740_p3(0) = '1') else 
        sobel_1_fu_729_p2;
    temp_fu_734_p2 <= std_logic_vector(unsigned(zext_ln58_1_fu_725_p1) + unsigned(zext_ln58_fu_722_p1));
    tmp3_fu_465_p2 <= std_logic_vector(signed(sext_ln77_cast_reg_812) + signed(src));
    tmp_1_fu_586_p4 <= out_pix_fu_572_p2(10 downto 8);
    tmp_3_fu_678_p4 <= out_pix_4_fu_664_p2(10 downto 8);
    tmp_4_fu_740_p3 <= temp_fu_734_p2(8 downto 8);
    tmp_fu_578_p3 <= out_pix_fu_572_p2(10 downto 10);
    trunc_ln27_fu_602_p1 <= out_pix_fu_572_p2(8 - 1 downto 0);
    trunc_ln49_fu_694_p1 <= out_pix_4_reg_975(8 - 1 downto 0);
    xor_ln27_fu_606_p2 <= (tmp_fu_578_p3 xor ap_const_lv1_1);
    xor_ln49_fu_697_p2 <= (tmp_2_reg_980 xor ap_const_lv1_1);
    xor_ln77_fu_299_p2 <= (icmp_ln80_fu_294_p2 xor ap_const_lv1_1);
    zext_ln10_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(M00_fu_481_p3),11));
    zext_ln11_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(M01_fu_492_p3),11));
    zext_ln12_1_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sobel_kernel_7_reg_963),10));
    zext_ln12_2_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sobel_kernel_7_reg_963),11));
    zext_ln12_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sobel_kernel_2_reg_928),9));
    zext_ln13_1_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sobel_kernel_5_reg_943),11));
    zext_ln13_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sobel_kernel_reg_918),9));
    zext_ln32_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(M00_1_fu_531_p3),10));
    zext_ln33_fu_641_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(M01_1_fu_634_p3),10));
    zext_ln34_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln34_1_fu_542_p2),10));
    zext_ln37_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln34_reg_953),11));
    zext_ln39_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln39_fu_654_p2),11));
    zext_ln58_1_fu_725_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_y_fu_714_p3),9));
    zext_ln58_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_x_reg_969),9));
    zext_ln77_cast_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln77),64));
    zext_ln80_1_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_fu_104),32));
    zext_ln80_2_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln80_fu_340_p3),32));
    zext_ln80_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln77_fu_377_p3),63));
end behav;
