// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sobel_sobel_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_80_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        mul_ln66,
        cols_cast6,
        src,
        cols_cast,
        sext_ln77,
        sub2,
        zext_ln77,
        dst
);

parameter    ap_ST_fsm_pp0_stage0 = 9'd1;
parameter    ap_ST_fsm_pp0_stage1 = 9'd2;
parameter    ap_ST_fsm_pp0_stage2 = 9'd4;
parameter    ap_ST_fsm_pp0_stage3 = 9'd8;
parameter    ap_ST_fsm_pp0_stage4 = 9'd16;
parameter    ap_ST_fsm_pp0_stage5 = 9'd32;
parameter    ap_ST_fsm_pp0_stage6 = 9'd64;
parameter    ap_ST_fsm_pp0_stage7 = 9'd128;
parameter    ap_ST_fsm_pp0_stage8 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [7:0] m_axi_gmem_WDATA;
output  [0:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [7:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [10:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] mul_ln66;
input  [31:0] cols_cast6;
input  [63:0] src;
input  [31:0] cols_cast;
input  [31:0] sext_ln77;
input  [31:0] sub2;
input  [30:0] zext_ln77;
input  [63:0] dst;

reg ap_idle;
reg m_axi_gmem_AWVALID;
reg m_axi_gmem_WVALID;
reg m_axi_gmem_ARVALID;
reg[63:0] m_axi_gmem_ARADDR;
reg m_axi_gmem_RREADY;
reg m_axi_gmem_BREADY;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage8;
reg    ap_block_state18_pp0_stage8_iter1;
reg    ap_block_pp0_stage8_subdone;
reg   [0:0] icmp_ln77_reg_833;
reg    ap_condition_exit_pp0_iter0_stage8;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage8;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg    gmem_blk_n_B;
reg   [0:0] icmp_ln80_1_reg_863;
reg   [0:0] icmp_ln80_1_reg_863_pp0_iter3_reg;
reg    gmem_blk_n_W;
reg    gmem_blk_n_AW;
reg   [0:0] or_ln77_reg_843;
reg   [0:0] first_iter_0_reg_223;
reg    ap_block_state10_io;
reg    ap_block_state19_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln77_cast_fu_240_p1;
reg   [63:0] zext_ln77_cast_reg_807;
wire  signed [63:0] sext_ln77_cast_fu_244_p1;
reg  signed [63:0] sext_ln77_cast_reg_812;
wire  signed [62:0] cols_cast_cast_fu_248_p1;
reg  signed [62:0] cols_cast_cast_reg_817;
wire  signed [32:0] cols_cast6_cast_fu_252_p1;
reg  signed [32:0] cols_cast6_cast_reg_823;
reg   [63:0] indvar_flatten_load_reg_828;
reg    ap_block_state20_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln77_fu_282_p2;
reg   [0:0] icmp_ln77_reg_833_pp0_iter1_reg;
reg   [0:0] icmp_ln77_reg_833_pp0_iter2_reg;
wire   [0:0] icmp_ln80_fu_294_p2;
reg   [0:0] icmp_ln80_reg_837;
wire   [0:0] or_ln77_fu_305_p2;
wire   [30:0] select_ln77_1_fu_317_p3;
reg   [30:0] select_ln77_1_reg_847;
wire   [30:0] add_ln80_fu_325_p2;
reg   [30:0] add_ln80_reg_853;
reg    ap_block_state21_pp0_stage2_iter2;
reg    ap_block_pp0_stage2_11001;
wire   [0:0] icmp_ln80_1_fu_350_p2;
reg   [0:0] icmp_ln80_1_reg_863_pp0_iter1_reg;
reg   [0:0] icmp_ln80_1_reg_863_pp0_iter2_reg;
wire  signed [62:0] grp_fu_236_p2;
reg  signed [62:0] mul_ln77_reg_867;
reg    ap_block_state22_pp0_stage3_iter2;
reg    ap_block_state31_pp0_stage3_iter3;
reg    ap_block_pp0_stage3_11001;
wire   [32:0] add_ln86_2_fu_369_p2;
reg   [32:0] add_ln86_2_reg_873;
reg   [63:0] gmem_addr_reg_878;
reg    ap_block_state23_pp0_stage4_iter2;
reg    ap_block_pp0_stage4_11001;
wire  signed [62:0] add_ln86_fu_410_p2;
reg  signed [62:0] add_ln86_reg_883;
reg   [63:0] gmem_addr_1_reg_895;
reg    ap_predicate_op97_writereq_state6;
reg    ap_block_state6_io;
reg    ap_block_state15_pp0_stage5_iter1;
reg    ap_block_pp0_stage5_11001;
wire   [62:0] empty_22_fu_447_p2;
reg   [62:0] empty_22_reg_901;
reg   [63:0] gmem_addr_2_reg_906;
reg    ap_block_state7_io;
reg    ap_block_state16_pp0_stage6_iter1;
reg    ap_block_pp0_stage6_11001;
reg   [63:0] gmem_addr_3_reg_912;
reg   [7:0] sobel_kernel_reg_918;
reg   [7:0] sobel_kernel_1_reg_923;
reg   [7:0] sobel_kernel_2_reg_928;
reg    ap_block_state17_pp0_stage7_iter1;
reg    ap_block_pp0_stage7_11001;
reg   [7:0] sobel_kernel_3_reg_933;
reg    ap_block_pp0_stage8_11001;
reg   [7:0] sobel_kernel_4_reg_938;
reg   [7:0] sobel_kernel_5_reg_943;
wire   [10:0] out_pix_5_fu_525_p2;
reg   [10:0] out_pix_5_reg_948;
wire   [9:0] add_ln34_fu_552_p2;
reg   [9:0] add_ln34_reg_953;
reg   [7:0] sobel_kernel_6_reg_958;
reg   [7:0] sobel_kernel_7_reg_963;
wire   [7:0] g_x_fu_626_p3;
reg   [7:0] g_x_reg_969;
wire   [10:0] out_pix_4_fu_664_p2;
reg   [10:0] out_pix_4_reg_975;
reg   [0:0] tmp_2_reg_980;
wire   [0:0] icmp_ln45_fu_688_p2;
reg   [0:0] icmp_ln45_reg_986;
wire   [7:0] sobel_2_fu_748_p3;
reg   [7:0] sobel_2_reg_991;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage3_subdone;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_228_p4;
wire    ap_loop_init;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] add_ln77_2_fu_387_p2;
wire   [63:0] empty_20_fu_436_p2;
wire   [63:0] empty_23_fu_454_p2;
wire   [63:0] empty_26_fu_469_p2;
reg    ap_block_pp0_stage7_01001;
reg   [30:0] col_fu_104;
wire   [30:0] select_ln80_fu_340_p3;
reg   [30:0] indvar3_fu_108;
wire   [30:0] add_ln80_1_fu_422_p2;
reg   [30:0] indvar_fu_112;
reg   [63:0] indvar_flatten_fu_116;
wire   [63:0] add_ln77_fu_331_p2;
wire   [30:0] grp_fu_236_p0;
wire  signed [31:0] grp_fu_236_p1;
wire   [31:0] zext_ln80_1_fu_290_p1;
wire   [0:0] xor_ln77_fu_299_p2;
wire   [30:0] add_ln77_1_fu_311_p2;
wire   [31:0] zext_ln80_2_fu_346_p1;
wire  signed [63:0] sext_ln77_1_fu_384_p1;
wire   [30:0] select_ln77_fu_377_p3;
wire   [62:0] zext_ln80_fu_398_p1;
wire  signed [62:0] sext_ln86_fu_407_p1;
wire   [62:0] add_ln86_1_fu_402_p2;
wire  signed [63:0] add_ln86_cast_fu_433_p1;
wire  signed [63:0] p_cast10_fu_451_p1;
wire   [63:0] tmp3_fu_465_p2;
wire   [8:0] M00_fu_481_p3;
wire   [8:0] M01_fu_492_p3;
wire   [8:0] zext_ln12_fu_503_p1;
wire   [8:0] zext_ln13_fu_506_p1;
wire   [8:0] S00_fu_509_p2;
wire  signed [10:0] sext_ln12_fu_515_p1;
wire   [10:0] zext_ln10_fu_488_p1;
wire   [10:0] A00_fu_519_p2;
wire   [10:0] zext_ln11_fu_499_p1;
wire   [8:0] M00_1_fu_531_p3;
wire   [8:0] add_ln34_1_fu_542_p2;
wire   [9:0] zext_ln34_fu_548_p1;
wire   [9:0] zext_ln32_fu_538_p1;
wire   [10:0] zext_ln13_1_fu_564_p1;
wire   [10:0] out_pix_6_fu_567_p2;
wire   [10:0] zext_ln12_2_fu_561_p1;
wire   [10:0] out_pix_fu_572_p2;
wire   [2:0] tmp_1_fu_586_p4;
wire   [0:0] tmp_fu_578_p3;
wire   [0:0] xor_ln27_fu_606_p2;
wire   [0:0] icmp_ln23_fu_596_p2;
wire   [0:0] or_ln27_fu_620_p2;
wire   [7:0] select_ln27_fu_612_p3;
wire   [7:0] trunc_ln27_fu_602_p1;
wire   [8:0] M01_1_fu_634_p3;
wire   [10:0] zext_ln37_fu_645_p1;
wire   [9:0] zext_ln33_fu_641_p1;
wire   [9:0] zext_ln12_1_fu_558_p1;
wire   [9:0] add_ln39_fu_654_p2;
wire   [10:0] zext_ln39_fu_660_p1;
wire   [10:0] out_pix_7_fu_648_p2;
wire   [2:0] tmp_3_fu_678_p4;
wire   [0:0] xor_ln49_fu_697_p2;
wire   [0:0] or_ln49_fu_710_p2;
wire   [7:0] select_ln49_fu_702_p3;
wire   [7:0] trunc_ln49_fu_694_p1;
wire   [7:0] g_y_fu_714_p3;
wire   [8:0] zext_ln58_1_fu_725_p1;
wire   [8:0] zext_ln58_fu_722_p1;
wire   [8:0] temp_fu_734_p2;
wire   [0:0] tmp_4_fu_740_p3;
wire   [7:0] sobel_1_fu_729_p2;
reg    grp_fu_236_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage3;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
reg    ap_done_pending_pp0;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_pp0_stage7_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [62:0] grp_fu_236_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 col_fu_104 = 31'd0;
#0 indvar3_fu_108 = 31'd0;
#0 indvar_fu_112 = 31'd0;
#0 indvar_flatten_fu_116 = 64'd0;
#0 ap_done_reg = 1'b0;
end

sobel_mul_31ns_32s_63_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_31ns_32s_63_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_236_p0),
    .din1(grp_fu_236_p1),
    .ce(grp_fu_236_ce),
    .dout(grp_fu_236_p2)
);

sobel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage8),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage8)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_fu_104 <= 31'd1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        col_fu_104 <= select_ln80_fu_340_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        first_iter_0_reg_223 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_0_reg_223 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar3_fu_108 <= 31'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        indvar3_fu_108 <= add_ln80_1_fu_422_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_fu_116 <= 64'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        indvar_flatten_fu_116 <= add_ln77_fu_331_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_fu_112 <= 31'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        indvar_fu_112 <= select_ln77_1_reg_847;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        add_ln34_reg_953 <= add_ln34_fu_552_p2;
        icmp_ln80_1_reg_863 <= icmp_ln80_1_fu_350_p2;
        icmp_ln80_1_reg_863_pp0_iter1_reg <= icmp_ln80_1_reg_863;
        icmp_ln80_1_reg_863_pp0_iter2_reg <= icmp_ln80_1_reg_863_pp0_iter1_reg;
        icmp_ln80_1_reg_863_pp0_iter3_reg <= icmp_ln80_1_reg_863_pp0_iter2_reg;
        out_pix_5_reg_948 <= out_pix_5_fu_525_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln80_reg_853 <= add_ln80_fu_325_p2;
        icmp_ln77_reg_833 <= icmp_ln77_fu_282_p2;
        icmp_ln77_reg_833_pp0_iter1_reg <= icmp_ln77_reg_833;
        icmp_ln77_reg_833_pp0_iter2_reg <= icmp_ln77_reg_833_pp0_iter1_reg;
        icmp_ln80_reg_837 <= icmp_ln80_fu_294_p2;
        indvar_flatten_load_reg_828 <= indvar_flatten_fu_116;
        or_ln77_reg_843 <= or_ln77_fu_305_p2;
        select_ln77_1_reg_847 <= select_ln77_1_fu_317_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        add_ln86_2_reg_873 <= add_ln86_2_fu_369_p2;
        mul_ln77_reg_867 <= grp_fu_236_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        add_ln86_reg_883 <= add_ln86_fu_410_p2;
        gmem_addr_reg_878 <= add_ln77_2_fu_387_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cols_cast6_cast_reg_823 <= cols_cast6_cast_fu_252_p1;
        cols_cast_cast_reg_817 <= cols_cast_cast_fu_248_p1;
        sext_ln77_cast_reg_812 <= sext_ln77_cast_fu_244_p1;
        zext_ln77_cast_reg_807[30 : 0] <= zext_ln77_cast_fu_240_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        empty_22_reg_901 <= empty_22_fu_447_p2;
        g_x_reg_969 <= g_x_fu_626_p3;
        gmem_addr_1_reg_895 <= empty_20_fu_436_p2;
        icmp_ln45_reg_986 <= icmp_ln45_fu_688_p2;
        out_pix_4_reg_975 <= out_pix_4_fu_664_p2;
        tmp_2_reg_980 <= out_pix_4_fu_664_p2[32'd10];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        gmem_addr_2_reg_906 <= empty_23_fu_454_p2;
        gmem_addr_3_reg_912 <= empty_26_fu_469_p2;
        sobel_2_reg_991 <= sobel_2_fu_748_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        sobel_kernel_1_reg_923 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        sobel_kernel_2_reg_928 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        sobel_kernel_3_reg_933 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sobel_kernel_4_reg_938 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        sobel_kernel_5_reg_943 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        sobel_kernel_6_reg_958 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        sobel_kernel_7_reg_963 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        sobel_kernel_reg_918 <= m_axi_gmem_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (icmp_ln77_reg_833 == 1'd1) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln77_reg_833_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_condition_exit_pp0_iter2_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        ap_phi_mux_first_iter_0_phi_fu_228_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_228_p4 = first_iter_0_reg_223;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln77_reg_843 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage5))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln80_1_reg_863_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)))) begin
        grp_fu_236_ce = 1'b1;
    end else begin
        grp_fu_236_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_3_reg_912;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_2_reg_906;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_1_reg_895;
    end else begin
        m_axi_gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln77_reg_833 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op97_writereq_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln80_1_reg_863_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A00_fu_519_p2 = ($signed(sext_ln12_fu_515_p1) - $signed(zext_ln10_fu_488_p1));

assign M00_1_fu_531_p3 = {{sobel_kernel_1_reg_923}, {1'd0}};

assign M00_fu_481_p3 = {{sobel_kernel_3_reg_933}, {1'd0}};

assign M01_1_fu_634_p3 = {{sobel_kernel_6_reg_958}, {1'd0}};

assign M01_fu_492_p3 = {{sobel_kernel_4_reg_938}, {1'd0}};

assign S00_fu_509_p2 = (zext_ln12_fu_503_p1 - zext_ln13_fu_506_p1);

assign add_ln34_1_fu_542_p2 = (zext_ln13_fu_506_p1 + zext_ln12_fu_503_p1);

assign add_ln34_fu_552_p2 = (zext_ln34_fu_548_p1 + zext_ln32_fu_538_p1);

assign add_ln39_fu_654_p2 = (zext_ln33_fu_641_p1 + zext_ln12_1_fu_558_p1);

assign add_ln77_1_fu_311_p2 = (indvar_fu_112 + 31'd1);

assign add_ln77_2_fu_387_p2 = ($signed(sext_ln77_1_fu_384_p1) + $signed(dst));

assign add_ln77_fu_331_p2 = (indvar_flatten_load_reg_828 + 64'd1);

assign add_ln80_1_fu_422_p2 = (select_ln77_fu_377_p3 + 31'd1);

assign add_ln80_fu_325_p2 = (col_fu_104 + 31'd1);

assign add_ln86_1_fu_402_p2 = ($signed(mul_ln77_reg_867) + $signed(zext_ln80_fu_398_p1));

assign add_ln86_2_fu_369_p2 = ($signed(cols_cast6_cast_reg_823) + $signed(33'd1));

assign add_ln86_cast_fu_433_p1 = add_ln86_reg_883;

assign add_ln86_fu_410_p2 = ($signed(sext_ln86_fu_407_p1) + $signed(add_ln86_1_fu_402_p2));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_io)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state20_pp0_stage1_iter2));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state20_pp0_stage1_iter2));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage2_iter2));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage2_iter2));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((m_axi_gmem_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state31_pp0_stage3_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((m_axi_gmem_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state31_pp0_stage3_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter2)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage4_iter2));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage4_iter2));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage5_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage5_iter1)));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_io)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage6_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_io)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage6_iter1)));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage7_iter1));
end

always @ (*) begin
    ap_block_pp0_stage7_11001 = (((m_axi_gmem_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage7_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = (((m_axi_gmem_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage7_iter1)));
end

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage8_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage8_iter1));
end

always @ (*) begin
    ap_block_pp0_stage8_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage8_iter1));
end

always @ (*) begin
    ap_block_state10_io = ((m_axi_gmem_ARREADY == 1'b0) & (icmp_ln77_reg_833 == 1'd0));
end

always @ (*) begin
    ap_block_state15_pp0_stage5_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state16_pp0_stage6_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state17_pp0_stage7_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state18_pp0_stage8_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state19_pp0_stage0_iter2 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state20_pp0_stage1_iter2 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state21_pp0_stage2_iter2 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state22_pp0_stage3_iter2 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state23_pp0_stage4_iter2 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state31_pp0_stage3_iter3 = ((m_axi_gmem_BVALID == 1'b0) & (icmp_ln80_1_reg_863_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_block_state6_io = ((m_axi_gmem_AWREADY == 1'b0) & (ap_predicate_op97_writereq_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state7_io = ((m_axi_gmem_ARREADY == 1'b0) & (icmp_ln77_reg_833 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage8;

always @ (*) begin
    ap_predicate_op97_writereq_state6 = ((or_ln77_reg_843 == 1'd1) & (icmp_ln77_reg_833 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign cols_cast6_cast_fu_252_p1 = $signed(cols_cast6);

assign cols_cast_cast_fu_248_p1 = $signed(cols_cast);

assign empty_20_fu_436_p2 = ($signed(add_ln86_cast_fu_433_p1) + $signed(src));

assign empty_22_fu_447_p2 = ($signed(add_ln86_reg_883) + $signed(cols_cast_cast_reg_817));

assign empty_23_fu_454_p2 = ($signed(p_cast10_fu_451_p1) + $signed(src));

assign empty_26_fu_469_p2 = ($signed(tmp3_fu_465_p2) + $signed(p_cast10_fu_451_p1));

assign g_x_fu_626_p3 = ((or_ln27_fu_620_p2[0:0] == 1'b1) ? select_ln27_fu_612_p3 : trunc_ln27_fu_602_p1);

assign g_y_fu_714_p3 = ((or_ln49_fu_710_p2[0:0] == 1'b1) ? select_ln49_fu_702_p3 : trunc_ln49_fu_694_p1);

assign grp_fu_236_p0 = grp_fu_236_p00;

assign grp_fu_236_p00 = select_ln77_1_reg_847;

assign grp_fu_236_p1 = cols_cast_cast_reg_817;

assign icmp_ln23_fu_596_p2 = (($signed(tmp_1_fu_586_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_688_p2 = (($signed(tmp_3_fu_678_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_282_p2 = ((indvar_flatten_fu_116 == mul_ln66) ? 1'b1 : 1'b0);

assign icmp_ln80_1_fu_350_p2 = (($signed(zext_ln80_2_fu_346_p1) < $signed(sub2)) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_294_p2 = (($signed(zext_ln80_1_fu_290_p1) < $signed(sub2)) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 64'd3;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = gmem_addr_reg_878;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = zext_ln77_cast_reg_807;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_WDATA = sobel_2_reg_991;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 1'd1;

assign m_axi_gmem_WUSER = 1'd0;

assign or_ln27_fu_620_p2 = (tmp_fu_578_p3 | icmp_ln23_fu_596_p2);

assign or_ln49_fu_710_p2 = (tmp_2_reg_980 | icmp_ln45_reg_986);

assign or_ln77_fu_305_p2 = (xor_ln77_fu_299_p2 | ap_phi_mux_first_iter_0_phi_fu_228_p4);

assign out_pix_4_fu_664_p2 = (zext_ln39_fu_660_p1 + out_pix_7_fu_648_p2);

assign out_pix_5_fu_525_p2 = (A00_fu_519_p2 + zext_ln11_fu_499_p1);

assign out_pix_6_fu_567_p2 = (out_pix_5_reg_948 - zext_ln13_1_fu_564_p1);

assign out_pix_7_fu_648_p2 = (zext_ln13_1_fu_564_p1 - zext_ln37_fu_645_p1);

assign out_pix_fu_572_p2 = (out_pix_6_fu_567_p2 + zext_ln12_2_fu_561_p1);

assign p_cast10_fu_451_p1 = $signed(empty_22_reg_901);

assign select_ln27_fu_612_p3 = ((xor_ln27_fu_606_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln49_fu_702_p3 = ((xor_ln49_fu_697_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln77_1_fu_317_p3 = ((icmp_ln80_fu_294_p2[0:0] == 1'b1) ? indvar_fu_112 : add_ln77_1_fu_311_p2);

assign select_ln77_fu_377_p3 = ((icmp_ln80_reg_837[0:0] == 1'b1) ? indvar3_fu_108 : 31'd0);

assign select_ln80_fu_340_p3 = ((icmp_ln80_reg_837[0:0] == 1'b1) ? add_ln80_reg_853 : 31'd2);

assign sext_ln12_fu_515_p1 = $signed(S00_fu_509_p2);

assign sext_ln77_1_fu_384_p1 = mul_ln77_reg_867;

assign sext_ln77_cast_fu_244_p1 = $signed(sext_ln77);

assign sext_ln86_fu_407_p1 = $signed(add_ln86_2_reg_873);

assign sobel_1_fu_729_p2 = (g_y_fu_714_p3 + g_x_reg_969);

assign sobel_2_fu_748_p3 = ((tmp_4_fu_740_p3[0:0] == 1'b1) ? 8'd255 : sobel_1_fu_729_p2);

assign temp_fu_734_p2 = (zext_ln58_1_fu_725_p1 + zext_ln58_fu_722_p1);

assign tmp3_fu_465_p2 = ($signed(sext_ln77_cast_reg_812) + $signed(src));

assign tmp_1_fu_586_p4 = {{out_pix_fu_572_p2[10:8]}};

assign tmp_3_fu_678_p4 = {{out_pix_4_fu_664_p2[10:8]}};

assign tmp_4_fu_740_p3 = temp_fu_734_p2[32'd8];

assign tmp_fu_578_p3 = out_pix_fu_572_p2[32'd10];

assign trunc_ln27_fu_602_p1 = out_pix_fu_572_p2[7:0];

assign trunc_ln49_fu_694_p1 = out_pix_4_reg_975[7:0];

assign xor_ln27_fu_606_p2 = (tmp_fu_578_p3 ^ 1'd1);

assign xor_ln49_fu_697_p2 = (tmp_2_reg_980 ^ 1'd1);

assign xor_ln77_fu_299_p2 = (icmp_ln80_fu_294_p2 ^ 1'd1);

assign zext_ln10_fu_488_p1 = M00_fu_481_p3;

assign zext_ln11_fu_499_p1 = M01_fu_492_p3;

assign zext_ln12_1_fu_558_p1 = sobel_kernel_7_reg_963;

assign zext_ln12_2_fu_561_p1 = sobel_kernel_7_reg_963;

assign zext_ln12_fu_503_p1 = sobel_kernel_2_reg_928;

assign zext_ln13_1_fu_564_p1 = sobel_kernel_5_reg_943;

assign zext_ln13_fu_506_p1 = sobel_kernel_reg_918;

assign zext_ln32_fu_538_p1 = M00_1_fu_531_p3;

assign zext_ln33_fu_641_p1 = M01_1_fu_634_p3;

assign zext_ln34_fu_548_p1 = add_ln34_1_fu_542_p2;

assign zext_ln37_fu_645_p1 = add_ln34_reg_953;

assign zext_ln39_fu_660_p1 = add_ln39_fu_654_p2;

assign zext_ln58_1_fu_725_p1 = g_y_fu_714_p3;

assign zext_ln58_fu_722_p1 = g_x_reg_969;

assign zext_ln77_cast_fu_240_p1 = zext_ln77;

assign zext_ln80_1_fu_290_p1 = col_fu_104;

assign zext_ln80_2_fu_346_p1 = select_ln80_fu_340_p3;

assign zext_ln80_fu_398_p1 = select_ln77_fu_377_p3;

always @ (posedge ap_clk) begin
    zext_ln77_cast_reg_807[63:31] <= 33'b000000000000000000000000000000000;
end

endmodule //sobel_sobel_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_80_2
