# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/robot/project/FPGA/ZedBoard/lab_4/lab_4.srcs/sources_1/ip/clk_core/clk_core.xci
# IP: The module: 'clk_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/robot/project/FPGA/ZedBoard/lab_4/lab_4.gen/sources_1/ip/clk_core/clk_core_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/robot/project/FPGA/ZedBoard/lab_4/lab_4.gen/sources_1/ip/clk_core/clk_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/robot/project/FPGA/ZedBoard/lab_4/lab_4.gen/sources_1/ip/clk_core/clk_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/robot/project/FPGA/ZedBoard/lab_4/lab_4.srcs/sources_1/ip/clk_core/clk_core.xci
# IP: The module: 'clk_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/robot/project/FPGA/ZedBoard/lab_4/lab_4.gen/sources_1/ip/clk_core/clk_core_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/robot/project/FPGA/ZedBoard/lab_4/lab_4.gen/sources_1/ip/clk_core/clk_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/robot/project/FPGA/ZedBoard/lab_4/lab_4.gen/sources_1/ip/clk_core/clk_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
