-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yuv_filter_yuv_filter_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mul_ln30 : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    p_yuv_channels_ch1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_yuv_channels_ch1_ce0 : OUT STD_LOGIC;
    p_yuv_channels_ch1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_yuv_channels_ch2_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_yuv_channels_ch2_ce0 : OUT STD_LOGIC;
    p_yuv_channels_ch2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_yuv_channels_ch3_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_yuv_channels_ch3_ce0 : OUT STD_LOGIC;
    p_yuv_channels_ch3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_scale_channels_ch1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_scale_channels_ch1_ce0 : OUT STD_LOGIC;
    p_scale_channels_ch1_we0 : OUT STD_LOGIC;
    p_scale_channels_ch1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_scale_channels_ch2_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_scale_channels_ch2_ce0 : OUT STD_LOGIC;
    p_scale_channels_ch2_we0 : OUT STD_LOGIC;
    p_scale_channels_ch2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_scale_channels_ch3_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    p_scale_channels_ch3_ce0 : OUT STD_LOGIC;
    p_scale_channels_ch3_we0 : OUT STD_LOGIC;
    p_scale_channels_ch3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    zext_ln163_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln164_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln165_1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of yuv_filter_yuv_filter_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln155_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln165_1_cast_fu_188_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln165_1_cast_reg_410 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln164_1_cast_fu_192_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln164_1_cast_reg_415 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln163_1_cast_fu_196_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln163_1_cast_reg_420 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln160_fu_302_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln160_reg_429 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln160_1_fu_324_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln160_1_reg_434 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln160_1_reg_434_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln160_1_reg_434_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal Y_reg_456 : STD_LOGIC_VECTOR (7 downto 0);
    signal U_reg_461 : STD_LOGIC_VECTOR (7 downto 0);
    signal V_reg_466 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1_reg_471 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln2_reg_476 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln3_reg_481 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal y_fu_68 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln158_fu_308_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal x_fu_72 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln155_fu_260_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal indvar_flatten6_fu_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln155_1_fu_224_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (31 downto 0);
    signal p_yuv_channels_ch1_ce0_local : STD_LOGIC;
    signal p_yuv_channels_ch2_ce0_local : STD_LOGIC;
    signal p_yuv_channels_ch3_ce0_local : STD_LOGIC;
    signal p_scale_channels_ch1_we0_local : STD_LOGIC;
    signal p_scale_channels_ch1_ce0_local : STD_LOGIC;
    signal p_scale_channels_ch2_we0_local : STD_LOGIC;
    signal p_scale_channels_ch2_ce0_local : STD_LOGIC;
    signal p_scale_channels_ch3_we0_local : STD_LOGIC;
    signal p_scale_channels_ch3_ce0_local : STD_LOGIC;
    signal icmp_ln158_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln155_fu_241_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln160_fu_268_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln160_1_fu_280_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl_fu_272_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal p_shl1_fu_284_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln144_fu_252_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln158_1_fu_292_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln160_fu_298_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal mul_ln163_fu_333_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln163_fu_333_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln164_fu_341_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln164_fu_341_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln165_fu_349_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln165_fu_349_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln163_fu_333_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln164_fu_341_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln165_fu_349_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln163_fu_333_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln164_fu_341_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln165_fu_349_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component yuv_filter_mul_8ns_8ns_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component yuv_filter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_8ns_15_1_1_U18 : component yuv_filter_mul_8ns_8ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln163_fu_333_p0,
        din1 => mul_ln163_fu_333_p1,
        dout => mul_ln163_fu_333_p2);

    mul_8ns_8ns_15_1_1_U19 : component yuv_filter_mul_8ns_8ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln164_fu_341_p0,
        din1 => mul_ln164_fu_341_p1,
        dout => mul_ln164_fu_341_p2);

    mul_8ns_8ns_15_1_1_U20 : component yuv_filter_mul_8ns_8ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln165_fu_349_p0,
        din1 => mul_ln165_fu_349_p1,
        dout => mul_ln165_fu_349_p2);

    flow_control_loop_pipe_sequential_init_U : component yuv_filter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten6_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln155_fu_218_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_76 <= add_ln155_1_fu_224_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_76 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    x_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_72 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    x_fu_72 <= select_ln155_fu_260_p3;
                end if;
            end if; 
        end if;
    end process;

    y_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_68 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    y_fu_68 <= add_ln158_fu_308_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                U_reg_461 <= p_yuv_channels_ch2_q0;
                V_reg_466 <= p_yuv_channels_ch3_q0;
                Y_reg_456 <= p_yuv_channels_ch1_q0;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                trunc_ln1_reg_471 <= mul_ln163_fu_333_p2(14 downto 7);
                trunc_ln2_reg_476 <= mul_ln164_fu_341_p2(14 downto 7);
                trunc_ln3_reg_481 <= mul_ln165_fu_349_p2(14 downto 7);
                    zext_ln160_1_reg_434(21 downto 0) <= zext_ln160_1_fu_324_p1(21 downto 0);
                    zext_ln160_1_reg_434_pp0_iter3_reg(21 downto 0) <= zext_ln160_1_reg_434(21 downto 0);
                    zext_ln160_1_reg_434_pp0_iter4_reg(21 downto 0) <= zext_ln160_1_reg_434_pp0_iter3_reg(21 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln160_reg_429 <= add_ln160_fu_302_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    zext_ln163_1_cast_reg_420(7 downto 0) <= zext_ln163_1_cast_fu_196_p1(7 downto 0);
                    zext_ln164_1_cast_reg_415(7 downto 0) <= zext_ln164_1_cast_fu_192_p1(7 downto 0);
                    zext_ln165_1_cast_reg_410(7 downto 0) <= zext_ln165_1_cast_fu_188_p1(7 downto 0);
            end if;
        end if;
    end process;
    zext_ln165_1_cast_reg_410(14 downto 8) <= "0000000";
    zext_ln164_1_cast_reg_415(14 downto 8) <= "0000000";
    zext_ln163_1_cast_reg_420(14 downto 8) <= "0000000";
    zext_ln160_1_reg_434(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln160_1_reg_434_pp0_iter3_reg(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln160_1_reg_434_pp0_iter4_reg(63 downto 22) <= "000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln155_1_fu_224_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv32_1));
    add_ln155_fu_241_p2 <= std_logic_vector(unsigned(x_fu_72) + unsigned(ap_const_lv16_1));
    add_ln158_1_fu_292_p2 <= std_logic_vector(unsigned(p_shl_fu_272_p3) + unsigned(p_shl1_fu_284_p3));
    add_ln158_fu_308_p2 <= std_logic_vector(unsigned(select_ln144_fu_252_p3) + unsigned(ap_const_lv16_1));
    add_ln160_fu_302_p2 <= std_logic_vector(unsigned(add_ln158_1_fu_292_p2) + unsigned(zext_ln160_fu_298_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln155_fu_218_p2)
    begin
        if (((icmp_ln155_fu_218_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_76;
        end if; 
    end process;

    icmp_ln155_fu_218_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = mul_ln30) else "0";
    icmp_ln158_fu_247_p2 <= "1" when (y_fu_68 = height) else "0";
    mul_ln163_fu_333_p0 <= mul_ln163_fu_333_p00(8 - 1 downto 0);
    mul_ln163_fu_333_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Y_reg_456),15));
    mul_ln163_fu_333_p1 <= zext_ln163_1_cast_reg_420(8 - 1 downto 0);
    mul_ln164_fu_341_p0 <= mul_ln164_fu_341_p00(8 - 1 downto 0);
    mul_ln164_fu_341_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(U_reg_461),15));
    mul_ln164_fu_341_p1 <= zext_ln164_1_cast_reg_415(8 - 1 downto 0);
    mul_ln165_fu_349_p0 <= mul_ln165_fu_349_p00(8 - 1 downto 0);
    mul_ln165_fu_349_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(V_reg_466),15));
    mul_ln165_fu_349_p1 <= zext_ln165_1_cast_reg_410(8 - 1 downto 0);
    p_scale_channels_ch1_address0 <= zext_ln160_1_reg_434_pp0_iter4_reg(22 - 1 downto 0);
    p_scale_channels_ch1_ce0 <= p_scale_channels_ch1_ce0_local;

    p_scale_channels_ch1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_scale_channels_ch1_ce0_local <= ap_const_logic_1;
        else 
            p_scale_channels_ch1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_scale_channels_ch1_d0 <= trunc_ln1_reg_471;
    p_scale_channels_ch1_we0 <= p_scale_channels_ch1_we0_local;

    p_scale_channels_ch1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_scale_channels_ch1_we0_local <= ap_const_logic_1;
        else 
            p_scale_channels_ch1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_scale_channels_ch2_address0 <= zext_ln160_1_reg_434_pp0_iter4_reg(22 - 1 downto 0);
    p_scale_channels_ch2_ce0 <= p_scale_channels_ch2_ce0_local;

    p_scale_channels_ch2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_scale_channels_ch2_ce0_local <= ap_const_logic_1;
        else 
            p_scale_channels_ch2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_scale_channels_ch2_d0 <= trunc_ln2_reg_476;
    p_scale_channels_ch2_we0 <= p_scale_channels_ch2_we0_local;

    p_scale_channels_ch2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_scale_channels_ch2_we0_local <= ap_const_logic_1;
        else 
            p_scale_channels_ch2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_scale_channels_ch3_address0 <= zext_ln160_1_reg_434_pp0_iter4_reg(22 - 1 downto 0);
    p_scale_channels_ch3_ce0 <= p_scale_channels_ch3_ce0_local;

    p_scale_channels_ch3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_scale_channels_ch3_ce0_local <= ap_const_logic_1;
        else 
            p_scale_channels_ch3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_scale_channels_ch3_d0 <= trunc_ln3_reg_481;
    p_scale_channels_ch3_we0 <= p_scale_channels_ch3_we0_local;

    p_scale_channels_ch3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_scale_channels_ch3_we0_local <= ap_const_logic_1;
        else 
            p_scale_channels_ch3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_fu_284_p3 <= (trunc_ln160_1_fu_280_p1 & ap_const_lv8_0);
    p_shl_fu_272_p3 <= (trunc_ln160_fu_268_p1 & ap_const_lv10_0);
    p_yuv_channels_ch1_address0 <= zext_ln160_1_fu_324_p1(22 - 1 downto 0);
    p_yuv_channels_ch1_ce0 <= p_yuv_channels_ch1_ce0_local;

    p_yuv_channels_ch1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_yuv_channels_ch1_ce0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_yuv_channels_ch2_address0 <= zext_ln160_1_fu_324_p1(22 - 1 downto 0);
    p_yuv_channels_ch2_ce0 <= p_yuv_channels_ch2_ce0_local;

    p_yuv_channels_ch2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_yuv_channels_ch2_ce0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_yuv_channels_ch3_address0 <= zext_ln160_1_fu_324_p1(22 - 1 downto 0);
    p_yuv_channels_ch3_ce0 <= p_yuv_channels_ch3_ce0_local;

    p_yuv_channels_ch3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_yuv_channels_ch3_ce0_local <= ap_const_logic_1;
        else 
            p_yuv_channels_ch3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln144_fu_252_p3 <= 
        ap_const_lv16_0 when (icmp_ln158_fu_247_p2(0) = '1') else 
        y_fu_68;
    select_ln155_fu_260_p3 <= 
        add_ln155_fu_241_p2 when (icmp_ln158_fu_247_p2(0) = '1') else 
        x_fu_72;
    trunc_ln160_1_fu_280_p1 <= select_ln155_fu_260_p3(14 - 1 downto 0);
    trunc_ln160_fu_268_p1 <= select_ln155_fu_260_p3(12 - 1 downto 0);
    zext_ln160_1_fu_324_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln160_reg_429),64));
    zext_ln160_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln144_fu_252_p3),22));
    zext_ln163_1_cast_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln163_1),15));
    zext_ln164_1_cast_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln164_1),15));
    zext_ln165_1_cast_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln165_1),15));
end behav;
