// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dct_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_2d_in_address0,
        buf_2d_in_ce0,
        buf_2d_in_q0,
        buf_2d_in_8_address0,
        buf_2d_in_8_ce0,
        buf_2d_in_8_q0,
        buf_2d_in_9_address0,
        buf_2d_in_9_ce0,
        buf_2d_in_9_q0,
        buf_2d_in_10_address0,
        buf_2d_in_10_ce0,
        buf_2d_in_10_q0,
        buf_2d_in_11_address0,
        buf_2d_in_11_ce0,
        buf_2d_in_11_q0,
        buf_2d_in_12_address0,
        buf_2d_in_12_ce0,
        buf_2d_in_12_q0,
        buf_2d_in_13_address0,
        buf_2d_in_13_ce0,
        buf_2d_in_13_q0,
        buf_2d_in_14_address0,
        buf_2d_in_14_ce0,
        buf_2d_in_14_q0,
        row_outbuf_address0,
        row_outbuf_ce0,
        row_outbuf_we0,
        row_outbuf_d0,
        dct_1d_dct_coeff_table_0_address0,
        dct_1d_dct_coeff_table_0_ce0,
        dct_1d_dct_coeff_table_0_q0,
        dct_1d_dct_coeff_table_1_address0,
        dct_1d_dct_coeff_table_1_ce0,
        dct_1d_dct_coeff_table_1_q0,
        dct_1d_dct_coeff_table_2_address0,
        dct_1d_dct_coeff_table_2_ce0,
        dct_1d_dct_coeff_table_2_q0,
        dct_1d_dct_coeff_table_3_address0,
        dct_1d_dct_coeff_table_3_ce0,
        dct_1d_dct_coeff_table_3_q0,
        dct_1d_dct_coeff_table_4_address0,
        dct_1d_dct_coeff_table_4_ce0,
        dct_1d_dct_coeff_table_4_q0,
        dct_1d_dct_coeff_table_5_address0,
        dct_1d_dct_coeff_table_5_ce0,
        dct_1d_dct_coeff_table_5_q0,
        dct_1d_dct_coeff_table_6_address0,
        dct_1d_dct_coeff_table_6_ce0,
        dct_1d_dct_coeff_table_6_q0,
        dct_1d_dct_coeff_table_7_address0,
        dct_1d_dct_coeff_table_7_ce0,
        dct_1d_dct_coeff_table_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] buf_2d_in_address0;
output   buf_2d_in_ce0;
input  [15:0] buf_2d_in_q0;
output  [2:0] buf_2d_in_8_address0;
output   buf_2d_in_8_ce0;
input  [15:0] buf_2d_in_8_q0;
output  [2:0] buf_2d_in_9_address0;
output   buf_2d_in_9_ce0;
input  [15:0] buf_2d_in_9_q0;
output  [2:0] buf_2d_in_10_address0;
output   buf_2d_in_10_ce0;
input  [15:0] buf_2d_in_10_q0;
output  [2:0] buf_2d_in_11_address0;
output   buf_2d_in_11_ce0;
input  [15:0] buf_2d_in_11_q0;
output  [2:0] buf_2d_in_12_address0;
output   buf_2d_in_12_ce0;
input  [15:0] buf_2d_in_12_q0;
output  [2:0] buf_2d_in_13_address0;
output   buf_2d_in_13_ce0;
input  [15:0] buf_2d_in_13_q0;
output  [2:0] buf_2d_in_14_address0;
output   buf_2d_in_14_ce0;
input  [15:0] buf_2d_in_14_q0;
output  [5:0] row_outbuf_address0;
output   row_outbuf_ce0;
output   row_outbuf_we0;
output  [15:0] row_outbuf_d0;
output  [2:0] dct_1d_dct_coeff_table_0_address0;
output   dct_1d_dct_coeff_table_0_ce0;
input  [13:0] dct_1d_dct_coeff_table_0_q0;
output  [2:0] dct_1d_dct_coeff_table_1_address0;
output   dct_1d_dct_coeff_table_1_ce0;
input  [14:0] dct_1d_dct_coeff_table_1_q0;
output  [2:0] dct_1d_dct_coeff_table_2_address0;
output   dct_1d_dct_coeff_table_2_ce0;
input  [14:0] dct_1d_dct_coeff_table_2_q0;
output  [2:0] dct_1d_dct_coeff_table_3_address0;
output   dct_1d_dct_coeff_table_3_ce0;
input  [14:0] dct_1d_dct_coeff_table_3_q0;
output  [2:0] dct_1d_dct_coeff_table_4_address0;
output   dct_1d_dct_coeff_table_4_ce0;
input  [14:0] dct_1d_dct_coeff_table_4_q0;
output  [2:0] dct_1d_dct_coeff_table_5_address0;
output   dct_1d_dct_coeff_table_5_ce0;
input  [14:0] dct_1d_dct_coeff_table_5_q0;
output  [2:0] dct_1d_dct_coeff_table_6_address0;
output   dct_1d_dct_coeff_table_6_ce0;
input  [14:0] dct_1d_dct_coeff_table_6_q0;
output  [2:0] dct_1d_dct_coeff_table_7_address0;
output   dct_1d_dct_coeff_table_7_ce0;
input  [14:0] dct_1d_dct_coeff_table_7_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_329_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln32_fu_384_p1;
reg   [63:0] zext_ln32_reg_595;
reg   [63:0] zext_ln32_reg_595_pp0_iter2_reg;
wire   [63:0] zext_ln13_fu_397_p1;
reg   [63:0] zext_ln13_reg_611;
wire   [5:0] add_ln19_8_fu_406_p2;
reg   [5:0] add_ln19_8_reg_622;
reg   [5:0] add_ln19_8_reg_622_pp0_iter2_reg;
reg   [5:0] add_ln19_8_reg_622_pp0_iter3_reg;
reg   [5:0] add_ln19_8_reg_622_pp0_iter4_reg;
reg   [5:0] add_ln19_8_reg_622_pp0_iter5_reg;
reg   [5:0] add_ln19_8_reg_622_pp0_iter6_reg;
reg   [5:0] add_ln19_8_reg_622_pp0_iter7_reg;
reg  signed [15:0] buf_2d_in_11_load_reg_712;
reg   [13:0] coeff_reg_727;
reg   [13:0] coeff_reg_727_pp0_iter4_reg;
reg  signed [14:0] coeff_1_reg_732;
reg   [14:0] coeff_2_reg_737;
reg  signed [14:0] coeff_2_reg_737_pp0_iter4_reg;
reg  signed [14:0] coeff_3_reg_742;
reg  signed [14:0] coeff_4_reg_747;
reg  signed [15:0] buf_2d_in_load_reg_762;
reg  signed [15:0] buf_2d_in_9_load_reg_772;
wire   [28:0] mul_ln19_5_fu_472_p2;
reg  signed [28:0] mul_ln19_5_reg_792;
wire   [28:0] mul_ln19_1_fu_490_p2;
reg  signed [28:0] mul_ln19_1_reg_797;
wire   [28:0] mul_ln19_7_fu_496_p2;
reg  signed [28:0] mul_ln19_7_reg_802;
wire   [28:0] grp_fu_529_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln19_6_fu_502_p2;
reg   [28:0] add_ln19_6_reg_812;
reg   [15:0] trunc_ln1_reg_817;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln19_2_fu_525_p1;
reg   [3:0] k_fu_78;
wire   [3:0] add_ln13_fu_412_p2;
wire    ap_loop_init;
reg   [3:0] i_fu_82;
wire   [3:0] select_ln32_fu_372_p3;
reg   [6:0] indvar_flatten6_fu_86;
wire   [6:0] add_ln32_1_fu_335_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    buf_2d_in_14_ce0_local;
reg    dct_1d_dct_coeff_table_7_ce0_local;
reg    buf_2d_in_11_ce0_local;
reg    buf_2d_in_12_ce0_local;
reg    buf_2d_in_13_ce0_local;
reg    dct_1d_dct_coeff_table_0_ce0_local;
reg    dct_1d_dct_coeff_table_1_ce0_local;
reg    dct_1d_dct_coeff_table_2_ce0_local;
reg    dct_1d_dct_coeff_table_3_ce0_local;
reg    dct_1d_dct_coeff_table_4_ce0_local;
reg    dct_1d_dct_coeff_table_5_ce0_local;
reg    dct_1d_dct_coeff_table_6_ce0_local;
reg    buf_2d_in_ce0_local;
reg    buf_2d_in_8_ce0_local;
reg    buf_2d_in_9_ce0_local;
reg    buf_2d_in_10_ce0_local;
reg    row_outbuf_we0_local;
reg    row_outbuf_ce0_local;
wire   [0:0] icmp_ln13_fu_358_p2;
wire   [3:0] add_ln32_fu_352_p2;
wire   [2:0] trunc_ln32_fu_380_p1;
wire   [3:0] select_ln28_fu_364_p3;
wire   [5:0] tmp_2_fu_389_p3;
wire   [5:0] zext_ln19_1_fu_402_p1;
wire   [13:0] mul_ln19_7_fu_496_p0;
wire  signed [28:0] add_ln19_6_fu_502_p0;
wire   [28:0] grp_fu_545_p3;
wire  signed [28:0] grp_fu_537_p3;
wire  signed [28:0] grp_fu_562_p3;
wire  signed [28:0] grp_fu_554_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln19_2_fu_506_p2;
wire   [28:0] add_ln19_7_fu_510_p2;
wire   [12:0] grp_fu_529_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [28:0] mul_ln19_7_fu_496_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 k_fu_78 = 4'd0;
#0 i_fu_82 = 4'd0;
#0 indvar_flatten6_fu_86 = 7'd0;
#0 ap_done_reg = 1'b0;
end

dct_mul_15s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_15s_16s_29_1_1_U10(
    .din0(coeff_4_reg_747),
    .din1(buf_2d_in_11_load_reg_712),
    .dout(mul_ln19_5_fu_472_p2)
);

dct_mul_15s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_15s_16s_29_1_1_U11(
    .din0(coeff_2_reg_737_pp0_iter4_reg),
    .din1(buf_2d_in_9_load_reg_772),
    .dout(mul_ln19_1_fu_490_p2)
);

dct_mul_14ns_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_14ns_16s_29_1_1_U12(
    .din0(mul_ln19_7_fu_496_p0),
    .din1(buf_2d_in_load_reg_762),
    .dout(mul_ln19_7_fu_496_p2)
);

dct_mac_muladd_16s_15s_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_13ns_29_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_2d_in_14_q0),
    .din1(dct_1d_dct_coeff_table_7_q0),
    .din2(grp_fu_529_p2),
    .ce(1'b1),
    .dout(grp_fu_529_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_2d_in_12_q0),
    .din1(dct_1d_dct_coeff_table_5_q0),
    .din2(mul_ln19_5_reg_792),
    .ce(1'b1),
    .dout(grp_fu_537_p3)
);

dct_mac_muladd_16s_15s_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29ns_29_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_2d_in_13_q0),
    .din1(dct_1d_dct_coeff_table_6_q0),
    .din2(grp_fu_529_p3),
    .ce(1'b1),
    .dout(grp_fu_545_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_2d_in_8_q0),
    .din1(coeff_1_reg_732),
    .din2(mul_ln19_7_reg_802),
    .ce(1'b1),
    .dout(grp_fu_554_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(buf_2d_in_10_q0),
    .din1(coeff_3_reg_742),
    .din2(mul_ln19_1_reg_797),
    .ce(1'b1),
    .dout(grp_fu_562_p3)
);

dct_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_82 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_82 <= select_ln32_fu_372_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln32_fu_329_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_86 <= add_ln32_1_fu_335_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_86 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_78 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            k_fu_78 <= add_ln13_fu_412_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln19_6_reg_812 <= add_ln19_6_fu_502_p2;
        add_ln19_8_reg_622_pp0_iter2_reg <= add_ln19_8_reg_622;
        add_ln19_8_reg_622_pp0_iter3_reg <= add_ln19_8_reg_622_pp0_iter2_reg;
        add_ln19_8_reg_622_pp0_iter4_reg <= add_ln19_8_reg_622_pp0_iter3_reg;
        add_ln19_8_reg_622_pp0_iter5_reg <= add_ln19_8_reg_622_pp0_iter4_reg;
        add_ln19_8_reg_622_pp0_iter6_reg <= add_ln19_8_reg_622_pp0_iter5_reg;
        add_ln19_8_reg_622_pp0_iter7_reg <= add_ln19_8_reg_622_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        buf_2d_in_11_load_reg_712 <= buf_2d_in_11_q0;
        buf_2d_in_9_load_reg_772 <= buf_2d_in_9_q0;
        buf_2d_in_load_reg_762 <= buf_2d_in_q0;
        coeff_1_reg_732 <= dct_1d_dct_coeff_table_1_q0;
        coeff_2_reg_737 <= dct_1d_dct_coeff_table_2_q0;
        coeff_2_reg_737_pp0_iter4_reg <= coeff_2_reg_737;
        coeff_3_reg_742 <= dct_1d_dct_coeff_table_3_q0;
        coeff_4_reg_747 <= dct_1d_dct_coeff_table_4_q0;
        coeff_reg_727 <= dct_1d_dct_coeff_table_0_q0;
        coeff_reg_727_pp0_iter4_reg <= coeff_reg_727;
        mul_ln19_1_reg_797 <= mul_ln19_1_fu_490_p2;
        mul_ln19_5_reg_792 <= mul_ln19_5_fu_472_p2;
        mul_ln19_7_reg_802 <= mul_ln19_7_fu_496_p2;
        trunc_ln1_reg_817 <= {{add_ln19_7_fu_510_p2[28:13]}};
        zext_ln32_reg_595_pp0_iter2_reg[3 : 0] <= zext_ln32_reg_595[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln19_8_reg_622 <= add_ln19_8_fu_406_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        zext_ln13_reg_611[3 : 0] <= zext_ln13_fu_397_p1[3 : 0];
        zext_ln32_reg_595[3 : 0] <= zext_ln32_fu_384_p1[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_329_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        buf_2d_in_10_ce0_local = 1'b1;
    end else begin
        buf_2d_in_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_2d_in_11_ce0_local = 1'b1;
    end else begin
        buf_2d_in_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_2d_in_12_ce0_local = 1'b1;
    end else begin
        buf_2d_in_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_2d_in_13_ce0_local = 1'b1;
    end else begin
        buf_2d_in_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_in_14_ce0_local = 1'b1;
    end else begin
        buf_2d_in_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        buf_2d_in_8_ce0_local = 1'b1;
    end else begin
        buf_2d_in_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        buf_2d_in_9_ce0_local = 1'b1;
    end else begin
        buf_2d_in_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        buf_2d_in_ce0_local = 1'b1;
    end else begin
        buf_2d_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dct_1d_dct_coeff_table_0_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dct_1d_dct_coeff_table_1_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dct_1d_dct_coeff_table_2_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dct_1d_dct_coeff_table_3_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dct_1d_dct_coeff_table_4_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dct_1d_dct_coeff_table_5_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dct_1d_dct_coeff_table_6_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dct_1d_dct_coeff_table_7_ce0_local = 1'b1;
    end else begin
        dct_1d_dct_coeff_table_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        row_outbuf_ce0_local = 1'b1;
    end else begin
        row_outbuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        row_outbuf_we0_local = 1'b1;
    end else begin
        row_outbuf_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_fu_412_p2 = (select_ln28_fu_364_p3 + 4'd1);

assign add_ln19_2_fu_506_p2 = ($signed(grp_fu_562_p3) + $signed(grp_fu_554_p3));

assign add_ln19_6_fu_502_p0 = grp_fu_545_p3;

assign add_ln19_6_fu_502_p2 = ($signed(add_ln19_6_fu_502_p0) + $signed(grp_fu_537_p3));

assign add_ln19_7_fu_510_p2 = (add_ln19_6_reg_812 + add_ln19_2_fu_506_p2);

assign add_ln19_8_fu_406_p2 = (tmp_2_fu_389_p3 + zext_ln19_1_fu_402_p1);

assign add_ln32_1_fu_335_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 7'd1);

assign add_ln32_fu_352_p2 = (i_fu_82 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buf_2d_in_10_address0 = zext_ln32_reg_595_pp0_iter2_reg;

assign buf_2d_in_10_ce0 = buf_2d_in_10_ce0_local;

assign buf_2d_in_11_address0 = zext_ln32_reg_595;

assign buf_2d_in_11_ce0 = buf_2d_in_11_ce0_local;

assign buf_2d_in_12_address0 = zext_ln32_reg_595;

assign buf_2d_in_12_ce0 = buf_2d_in_12_ce0_local;

assign buf_2d_in_13_address0 = zext_ln32_reg_595;

assign buf_2d_in_13_ce0 = buf_2d_in_13_ce0_local;

assign buf_2d_in_14_address0 = zext_ln32_fu_384_p1;

assign buf_2d_in_14_ce0 = buf_2d_in_14_ce0_local;

assign buf_2d_in_8_address0 = zext_ln32_reg_595_pp0_iter2_reg;

assign buf_2d_in_8_ce0 = buf_2d_in_8_ce0_local;

assign buf_2d_in_9_address0 = zext_ln32_reg_595_pp0_iter2_reg;

assign buf_2d_in_9_ce0 = buf_2d_in_9_ce0_local;

assign buf_2d_in_address0 = zext_ln32_reg_595_pp0_iter2_reg;

assign buf_2d_in_ce0 = buf_2d_in_ce0_local;

assign dct_1d_dct_coeff_table_0_address0 = zext_ln13_reg_611;

assign dct_1d_dct_coeff_table_0_ce0 = dct_1d_dct_coeff_table_0_ce0_local;

assign dct_1d_dct_coeff_table_1_address0 = zext_ln13_reg_611;

assign dct_1d_dct_coeff_table_1_ce0 = dct_1d_dct_coeff_table_1_ce0_local;

assign dct_1d_dct_coeff_table_2_address0 = zext_ln13_reg_611;

assign dct_1d_dct_coeff_table_2_ce0 = dct_1d_dct_coeff_table_2_ce0_local;

assign dct_1d_dct_coeff_table_3_address0 = zext_ln13_reg_611;

assign dct_1d_dct_coeff_table_3_ce0 = dct_1d_dct_coeff_table_3_ce0_local;

assign dct_1d_dct_coeff_table_4_address0 = zext_ln13_reg_611;

assign dct_1d_dct_coeff_table_4_ce0 = dct_1d_dct_coeff_table_4_ce0_local;

assign dct_1d_dct_coeff_table_5_address0 = zext_ln13_reg_611;

assign dct_1d_dct_coeff_table_5_ce0 = dct_1d_dct_coeff_table_5_ce0_local;

assign dct_1d_dct_coeff_table_6_address0 = zext_ln13_reg_611;

assign dct_1d_dct_coeff_table_6_ce0 = dct_1d_dct_coeff_table_6_ce0_local;

assign dct_1d_dct_coeff_table_7_address0 = zext_ln13_fu_397_p1;

assign dct_1d_dct_coeff_table_7_ce0 = dct_1d_dct_coeff_table_7_ce0_local;

assign grp_fu_529_p2 = 29'd4096;

assign icmp_ln13_fu_358_p2 = ((k_fu_78 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_329_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 7'd64) ? 1'b1 : 1'b0);

assign mul_ln19_7_fu_496_p0 = mul_ln19_7_fu_496_p00;

assign mul_ln19_7_fu_496_p00 = coeff_reg_727_pp0_iter4_reg;

assign row_outbuf_address0 = zext_ln19_2_fu_525_p1;

assign row_outbuf_ce0 = row_outbuf_ce0_local;

assign row_outbuf_d0 = trunc_ln1_reg_817;

assign row_outbuf_we0 = row_outbuf_we0_local;

assign select_ln28_fu_364_p3 = ((icmp_ln13_fu_358_p2[0:0] == 1'b1) ? 4'd0 : k_fu_78);

assign select_ln32_fu_372_p3 = ((icmp_ln13_fu_358_p2[0:0] == 1'b1) ? add_ln32_fu_352_p2 : i_fu_82);

assign tmp_2_fu_389_p3 = {{trunc_ln32_fu_380_p1}, {3'd0}};

assign trunc_ln32_fu_380_p1 = select_ln32_fu_372_p3[2:0];

assign zext_ln13_fu_397_p1 = select_ln28_fu_364_p3;

assign zext_ln19_1_fu_402_p1 = select_ln28_fu_364_p3;

assign zext_ln19_2_fu_525_p1 = add_ln19_8_reg_622_pp0_iter7_reg;

assign zext_ln32_fu_384_p1 = select_ln32_fu_372_p3;

always @ (posedge ap_clk) begin
    zext_ln32_reg_595[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_595_pp0_iter2_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln13_reg_611[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //dct_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop
