# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/robot/project/FPGA/sample/ps_pl_button/vivado/ps_pl_button/ps_pl_button.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
# IP: The module: 'design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/robot/project/FPGA/sample/ps_pl_button/vivado/ps_pl_button/ps_pl_button.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/robot/project/FPGA/sample/ps_pl_button/vivado/ps_pl_button/ps_pl_button.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/robot/project/FPGA/sample/ps_pl_button/vivado/ps_pl_button/ps_pl_button.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/robot/project/FPGA/sample/ps_pl_button/vivado/ps_pl_button/ps_pl_button.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
# IP: The module: 'design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/robot/project/FPGA/sample/ps_pl_button/vivado/ps_pl_button/ps_pl_button.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/robot/project/FPGA/sample/ps_pl_button/vivado/ps_pl_button/ps_pl_button.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/robot/project/FPGA/sample/ps_pl_button/vivado/ps_pl_button/ps_pl_button.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
