// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module yuv_filter_yuv_filter_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln30,
        height,
        p_yuv_channels_ch1_address0,
        p_yuv_channels_ch1_ce0,
        p_yuv_channels_ch1_q0,
        p_yuv_channels_ch2_address0,
        p_yuv_channels_ch2_ce0,
        p_yuv_channels_ch2_q0,
        p_yuv_channels_ch3_address0,
        p_yuv_channels_ch3_ce0,
        p_yuv_channels_ch3_q0,
        p_scale_channels_ch1_address0,
        p_scale_channels_ch1_ce0,
        p_scale_channels_ch1_we0,
        p_scale_channels_ch1_d0,
        p_scale_channels_ch2_address0,
        p_scale_channels_ch2_ce0,
        p_scale_channels_ch2_we0,
        p_scale_channels_ch2_d0,
        p_scale_channels_ch3_address0,
        p_scale_channels_ch3_ce0,
        p_scale_channels_ch3_we0,
        p_scale_channels_ch3_d0,
        zext_ln163_1,
        zext_ln164_1,
        zext_ln165_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mul_ln30;
input  [15:0] height;
output  [21:0] p_yuv_channels_ch1_address0;
output   p_yuv_channels_ch1_ce0;
input  [7:0] p_yuv_channels_ch1_q0;
output  [21:0] p_yuv_channels_ch2_address0;
output   p_yuv_channels_ch2_ce0;
input  [7:0] p_yuv_channels_ch2_q0;
output  [21:0] p_yuv_channels_ch3_address0;
output   p_yuv_channels_ch3_ce0;
input  [7:0] p_yuv_channels_ch3_q0;
output  [21:0] p_scale_channels_ch1_address0;
output   p_scale_channels_ch1_ce0;
output   p_scale_channels_ch1_we0;
output  [7:0] p_scale_channels_ch1_d0;
output  [21:0] p_scale_channels_ch2_address0;
output   p_scale_channels_ch2_ce0;
output   p_scale_channels_ch2_we0;
output  [7:0] p_scale_channels_ch2_d0;
output  [21:0] p_scale_channels_ch3_address0;
output   p_scale_channels_ch3_ce0;
output   p_scale_channels_ch3_we0;
output  [7:0] p_scale_channels_ch3_d0;
input  [7:0] zext_ln163_1;
input  [7:0] zext_ln164_1;
input  [7:0] zext_ln165_1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln155_fu_218_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [14:0] zext_ln165_1_cast_fu_188_p1;
reg   [14:0] zext_ln165_1_cast_reg_410;
wire   [14:0] zext_ln164_1_cast_fu_192_p1;
reg   [14:0] zext_ln164_1_cast_reg_415;
wire   [14:0] zext_ln163_1_cast_fu_196_p1;
reg   [14:0] zext_ln163_1_cast_reg_420;
wire   [21:0] add_ln160_fu_302_p2;
reg   [21:0] add_ln160_reg_429;
wire   [63:0] zext_ln160_1_fu_324_p1;
reg   [63:0] zext_ln160_1_reg_434;
reg   [63:0] zext_ln160_1_reg_434_pp0_iter3_reg;
reg   [63:0] zext_ln160_1_reg_434_pp0_iter4_reg;
reg   [7:0] Y_reg_456;
reg   [7:0] U_reg_461;
reg   [7:0] V_reg_466;
reg   [7:0] trunc_ln1_reg_471;
reg   [7:0] trunc_ln2_reg_476;
reg   [7:0] trunc_ln3_reg_481;
wire    ap_block_pp0_stage0;
reg   [15:0] y_fu_68;
wire   [15:0] add_ln158_fu_308_p2;
wire    ap_loop_init;
reg   [15:0] x_fu_72;
wire   [15:0] select_ln155_fu_260_p3;
reg   [31:0] indvar_flatten6_fu_76;
wire   [31:0] add_ln155_1_fu_224_p2;
reg   [31:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    p_yuv_channels_ch1_ce0_local;
reg    p_yuv_channels_ch2_ce0_local;
reg    p_yuv_channels_ch3_ce0_local;
reg    p_scale_channels_ch1_we0_local;
reg    p_scale_channels_ch1_ce0_local;
reg    p_scale_channels_ch2_we0_local;
reg    p_scale_channels_ch2_ce0_local;
reg    p_scale_channels_ch3_we0_local;
reg    p_scale_channels_ch3_ce0_local;
wire   [0:0] icmp_ln158_fu_247_p2;
wire   [15:0] add_ln155_fu_241_p2;
wire   [11:0] trunc_ln160_fu_268_p1;
wire   [13:0] trunc_ln160_1_fu_280_p1;
wire   [21:0] p_shl_fu_272_p3;
wire   [21:0] p_shl1_fu_284_p3;
wire   [15:0] select_ln144_fu_252_p3;
wire   [21:0] add_ln158_1_fu_292_p2;
wire   [21:0] zext_ln160_fu_298_p1;
wire   [7:0] mul_ln163_fu_333_p0;
wire   [7:0] mul_ln163_fu_333_p1;
wire   [7:0] mul_ln164_fu_341_p0;
wire   [7:0] mul_ln164_fu_341_p1;
wire   [7:0] mul_ln165_fu_349_p0;
wire   [7:0] mul_ln165_fu_349_p1;
wire   [14:0] mul_ln163_fu_333_p2;
wire   [14:0] mul_ln164_fu_341_p2;
wire   [14:0] mul_ln165_fu_349_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] mul_ln163_fu_333_p00;
wire   [14:0] mul_ln164_fu_341_p00;
wire   [14:0] mul_ln165_fu_349_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 y_fu_68 = 16'd0;
#0 x_fu_72 = 16'd0;
#0 indvar_flatten6_fu_76 = 32'd0;
#0 ap_done_reg = 1'b0;
end

yuv_filter_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U18(
    .din0(mul_ln163_fu_333_p0),
    .din1(mul_ln163_fu_333_p1),
    .dout(mul_ln163_fu_333_p2)
);

yuv_filter_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U19(
    .din0(mul_ln164_fu_341_p0),
    .din1(mul_ln164_fu_341_p1),
    .dout(mul_ln164_fu_341_p2)
);

yuv_filter_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U20(
    .din0(mul_ln165_fu_349_p0),
    .din1(mul_ln165_fu_349_p1),
    .dout(mul_ln165_fu_349_p2)
);

yuv_filter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln155_fu_218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_76 <= add_ln155_1_fu_224_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_76 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_72 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            x_fu_72 <= select_ln155_fu_260_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            y_fu_68 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            y_fu_68 <= add_ln158_fu_308_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        U_reg_461 <= p_yuv_channels_ch2_q0;
        V_reg_466 <= p_yuv_channels_ch3_q0;
        Y_reg_456 <= p_yuv_channels_ch1_q0;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        trunc_ln1_reg_471 <= {{mul_ln163_fu_333_p2[14:7]}};
        trunc_ln2_reg_476 <= {{mul_ln164_fu_341_p2[14:7]}};
        trunc_ln3_reg_481 <= {{mul_ln165_fu_349_p2[14:7]}};
        zext_ln160_1_reg_434[21 : 0] <= zext_ln160_1_fu_324_p1[21 : 0];
        zext_ln160_1_reg_434_pp0_iter3_reg[21 : 0] <= zext_ln160_1_reg_434[21 : 0];
        zext_ln160_1_reg_434_pp0_iter4_reg[21 : 0] <= zext_ln160_1_reg_434_pp0_iter3_reg[21 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln160_reg_429 <= add_ln160_fu_302_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        zext_ln163_1_cast_reg_420[7 : 0] <= zext_ln163_1_cast_fu_196_p1[7 : 0];
        zext_ln164_1_cast_reg_415[7 : 0] <= zext_ln164_1_cast_fu_192_p1[7 : 0];
        zext_ln165_1_cast_reg_410[7 : 0] <= zext_ln165_1_cast_fu_188_p1[7 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_218_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 32'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_scale_channels_ch1_ce0_local = 1'b1;
    end else begin
        p_scale_channels_ch1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_scale_channels_ch1_we0_local = 1'b1;
    end else begin
        p_scale_channels_ch1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_scale_channels_ch2_ce0_local = 1'b1;
    end else begin
        p_scale_channels_ch2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_scale_channels_ch2_we0_local = 1'b1;
    end else begin
        p_scale_channels_ch2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_scale_channels_ch3_ce0_local = 1'b1;
    end else begin
        p_scale_channels_ch3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_scale_channels_ch3_we0_local = 1'b1;
    end else begin
        p_scale_channels_ch3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_yuv_channels_ch1_ce0_local = 1'b1;
    end else begin
        p_yuv_channels_ch1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_yuv_channels_ch2_ce0_local = 1'b1;
    end else begin
        p_yuv_channels_ch2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_yuv_channels_ch3_ce0_local = 1'b1;
    end else begin
        p_yuv_channels_ch3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln155_1_fu_224_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 32'd1);

assign add_ln155_fu_241_p2 = (x_fu_72 + 16'd1);

assign add_ln158_1_fu_292_p2 = (p_shl_fu_272_p3 + p_shl1_fu_284_p3);

assign add_ln158_fu_308_p2 = (select_ln144_fu_252_p3 + 16'd1);

assign add_ln160_fu_302_p2 = (add_ln158_1_fu_292_p2 + zext_ln160_fu_298_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln155_fu_218_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == mul_ln30) ? 1'b1 : 1'b0);

assign icmp_ln158_fu_247_p2 = ((y_fu_68 == height) ? 1'b1 : 1'b0);

assign mul_ln163_fu_333_p0 = mul_ln163_fu_333_p00;

assign mul_ln163_fu_333_p00 = Y_reg_456;

assign mul_ln163_fu_333_p1 = zext_ln163_1_cast_reg_420;

assign mul_ln164_fu_341_p0 = mul_ln164_fu_341_p00;

assign mul_ln164_fu_341_p00 = U_reg_461;

assign mul_ln164_fu_341_p1 = zext_ln164_1_cast_reg_415;

assign mul_ln165_fu_349_p0 = mul_ln165_fu_349_p00;

assign mul_ln165_fu_349_p00 = V_reg_466;

assign mul_ln165_fu_349_p1 = zext_ln165_1_cast_reg_410;

assign p_scale_channels_ch1_address0 = zext_ln160_1_reg_434_pp0_iter4_reg;

assign p_scale_channels_ch1_ce0 = p_scale_channels_ch1_ce0_local;

assign p_scale_channels_ch1_d0 = trunc_ln1_reg_471;

assign p_scale_channels_ch1_we0 = p_scale_channels_ch1_we0_local;

assign p_scale_channels_ch2_address0 = zext_ln160_1_reg_434_pp0_iter4_reg;

assign p_scale_channels_ch2_ce0 = p_scale_channels_ch2_ce0_local;

assign p_scale_channels_ch2_d0 = trunc_ln2_reg_476;

assign p_scale_channels_ch2_we0 = p_scale_channels_ch2_we0_local;

assign p_scale_channels_ch3_address0 = zext_ln160_1_reg_434_pp0_iter4_reg;

assign p_scale_channels_ch3_ce0 = p_scale_channels_ch3_ce0_local;

assign p_scale_channels_ch3_d0 = trunc_ln3_reg_481;

assign p_scale_channels_ch3_we0 = p_scale_channels_ch3_we0_local;

assign p_shl1_fu_284_p3 = {{trunc_ln160_1_fu_280_p1}, {8'd0}};

assign p_shl_fu_272_p3 = {{trunc_ln160_fu_268_p1}, {10'd0}};

assign p_yuv_channels_ch1_address0 = zext_ln160_1_fu_324_p1;

assign p_yuv_channels_ch1_ce0 = p_yuv_channels_ch1_ce0_local;

assign p_yuv_channels_ch2_address0 = zext_ln160_1_fu_324_p1;

assign p_yuv_channels_ch2_ce0 = p_yuv_channels_ch2_ce0_local;

assign p_yuv_channels_ch3_address0 = zext_ln160_1_fu_324_p1;

assign p_yuv_channels_ch3_ce0 = p_yuv_channels_ch3_ce0_local;

assign select_ln144_fu_252_p3 = ((icmp_ln158_fu_247_p2[0:0] == 1'b1) ? 16'd0 : y_fu_68);

assign select_ln155_fu_260_p3 = ((icmp_ln158_fu_247_p2[0:0] == 1'b1) ? add_ln155_fu_241_p2 : x_fu_72);

assign trunc_ln160_1_fu_280_p1 = select_ln155_fu_260_p3[13:0];

assign trunc_ln160_fu_268_p1 = select_ln155_fu_260_p3[11:0];

assign zext_ln160_1_fu_324_p1 = add_ln160_reg_429;

assign zext_ln160_fu_298_p1 = select_ln144_fu_252_p3;

assign zext_ln163_1_cast_fu_196_p1 = zext_ln163_1;

assign zext_ln164_1_cast_fu_192_p1 = zext_ln164_1;

assign zext_ln165_1_cast_fu_188_p1 = zext_ln165_1;

always @ (posedge ap_clk) begin
    zext_ln165_1_cast_reg_410[14:8] <= 7'b0000000;
    zext_ln164_1_cast_reg_415[14:8] <= 7'b0000000;
    zext_ln163_1_cast_reg_420[14:8] <= 7'b0000000;
    zext_ln160_1_reg_434[63:22] <= 42'b000000000000000000000000000000000000000000;
    zext_ln160_1_reg_434_pp0_iter3_reg[63:22] <= 42'b000000000000000000000000000000000000000000;
    zext_ln160_1_reg_434_pp0_iter4_reg[63:22] <= 42'b000000000000000000000000000000000000000000;
end

endmodule //yuv_filter_yuv_filter_Pipeline_YUV_SCALE_LOOP_X_YUV_SCALE_LOOP_Y
