# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/robot/project/FPGA/sample/UART_sample/UART_sample.srcs/sources_1/bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xci
# IP: The module: 'UART_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/robot/project/FPGA/sample/UART_sample/UART_sample.gen/sources_1/bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/robot/project/FPGA/sample/UART_sample/UART_sample.srcs/sources_1/bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xci
# IP: The module: 'UART_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/robot/project/FPGA/sample/UART_sample/UART_sample.gen/sources_1/bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
